### ISSUE TITLE
Testnet Addresses?

### ISSUE THREAD

**Issue by robsecord** [mikedeshazer/OrFeedSmartContracts#1]
Do you have Testnet Addresses for the OrFeed interface yet?  Ropsten or Kovan?

**Comment by mikedeshazer** [comment]
We will be adding Testnet support soon. The biggesty issue here is that orfeed converts token symbols to token addresses and then uses them for uniswap, Kyber etc. So all of those contracts need to updated tested... it wont be as simple as posting to Kovan or Ropsten because of all the integrations. Will post to Gitcoin soon as a bounty in the Proof repo. Then, close this issue once there's a merge in.

**Comment by mikedeshazer** [comment]
@robsecord testnet addresses have been added to the bottom of README and contracts in the contracts folder. Please let us know if you have any issues with it...
